version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DB: esp_data
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esp_data
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: